### ISSUE TITLE
the application crashes when i click 'START SPOTTING' button

### ISSUE THREAD

**Issue by suihansong** [jimin530/VoiceRecognition_siri#1]
the application crashes when i click 'START SPOTTING' button.
here is the partial log:
![3](https://cloud.githubusercontent.com/assets/7686706/17545466/c398b740-5f0f-11e6-916b-6bf33749aec1.png)
![4](https://cloud.githubusercontent.com/assets/7686706/17545506/0c831ec8-5f10-11e6-8a6b-fa1c886493c3.png)

does it because of jnilib?
thanks!

**Comment by jimin530** [comment]
Maybe It is due to permission.
I changed code. Please try again.
Thank you.
